Add upload report builder
Spideo/rumo-sdk-python pull request #19
Opened 2024-04-29 09:04 UTC by araux1

2024-04-29 09:37 UTC, j-abi requested changes

2024-04-29 09:37 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +            if content["id"]:
bizarre cette condition, qu'est-ce que tu essaies de vérifier ?

2024-04-29 09:37 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +    def get_processed_content_ids(catalog) -> list[str]:
c'est une méthode statique ?

2024-04-29 09:37 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +    def get_validation_errors(cls, upload_responses) -> list[ValidationError]:
classmethod?

2024-04-29 09:37 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +    def build_validation_errors(response, validation_errors) -> ValidationError:
staticmethod ?

2024-04-29 09:37 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +    def get_invalid_content(cls, validation_errors: list[ValidationError]) -> list[str]:
classmethod ?

2024-04-29 09:37 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +class UploadReport:
au final dans la classe `UploadReport` il n'y a que des fonctions pour construire le `UploadReport`, aucune méthode spécifique à définir sur le rapport lui-même ?

(c'est juste un constat, je ne sais pas si c'est OK comme "pattern")

2024-04-29 13:31 UTC, j-abi requested changes

2024-04-29 13:31 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +    def build_validation_errors(response, validation_errors):
I think it would be more readable (and testable) for this function to return a list of objects, rather than to append to an existing list of objects

2024-04-29 13:31 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +            cls.build_validation_errors(response, validation_errors)
```suggestion
            validation_errors.append(cls.build_validation_errors(response))
```
(see other comment below)

2024-04-29 13:31 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +    def build_report(cls, catalog, upload_responses):
please specify input and output types

2024-04-29 13:31 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +    def get_processed_content_ids(catalog) -> set[str]:
please specify input type

2024-04-29 13:31 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +    def build_validation_errors(response, validation_errors):
also type hints are missing :wink:

2024-04-29 13:31 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +        self.processed_content = processed_content
processed means both successful and invalid ?

2024-04-29 13:31 UTC, j-abi commented on src/rumo_sdk/upload_report.py
> +            if content_id:
```suggestion
            if content_id is not None:
```
https://peps.python.org/pep-0008/#programming-recommendations

2024-04-30 07:55 UTC, j-abi approved these changes

2024-04-30 08:10 UTC, khouloudsa approved these changes

2024-04-30 12:09 UTC, merged